# possible values: trace, debug, info, warn, error
log_level = "debug"

# 0.0.0.0:8000 to expose outside of localhost
# default: "127.0.0.1:8000"
http_host = "127.0.0.1:8000"

# defines where the gRPC host is exposed
# default: "" gRPC is not exposed by default
grpc_host = "127.0.0.1:8001"

# Defines on which chain the wallet runs. Allowed values: main, testnet, signet, regtest.
# default: signet
chain = "signet"

# bitcoin core rpc endpoint
# default: http://127.0.0.1:8332
core_rpc_endpoint = "http://127.0.0.1:18443"

# bitcoin core rest endpoint
# note: requires bitcoin core PR #32540 (already merged to master but in a release yet)
# default: ""
core_rest_endpoint = "http://127.0.01:38332"

# required, unless rpc_user and rpc_pass are set
cookie_path = ""

# required, unless cookie_path is set
rpc_pass = "your-rpc-password"

# required, unless cookie_path is set
rpc_user = "your-rpc-user"

# required (has to be >= 1)
sync_start_height = 1

# the default for this is 1, but should be set to a higher value to increase performance, 
# one should set this in accordance to how many cores one wants to use
max_parallel_tweak_computations = 4

# (depends on max-rpc-workers of the underlying full node)
max_parallel_requests = 4

# optional - will only generate tweaks (still both cut-through and full-index)
# default: 0
tweaks_only = 0

# The base index. Only includes the tweaks. No dust filtering or cut-through possible
# default: 1
tweaks_full_basic = 1

# if this is set a full non-cut-through index will be created.
# This index can be used to filter for dust (?dustLimit=). If this is active the base index will not be created.
# All full index queries will be served from this with or without (?dustLimit=) set in the query.
# default 0
tweaks_full_with_dust_filter = 0

# This index applies cut-through and dust filtering.
# Beware that it will be stored in addition to any full index (with or without dust) if activated.
# It has more storage requirements than the simple indices.
# Currently still requires tweaks_only=0.
# default: 0
tweaks_cut_through_with_dust_filter = 0
